name: CI

on: [push, pull_request]

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python1
        run: python3 -m venv .venv
      - name: Setup python2
        run: source .venv/bin/activate
      - name: Setup python3
        run: pip install -r requirements.txt
      - name: Install browsers
        run: playwright install
      - name: Pwd
        run: echo pwd
      - name: Run app
        run: npm run serve
        working-directory: ./web/simple-app
      - name: Run tests
        run: pytest