name: CI

on: [push, pull_request]

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python venv
        run: python3 -m venv .venv
      - name: Activate python venv
        run: source .venv/bin/activate
      - name: Install python requirements
        run: pip install -r requirements.txt
      - name: Install playwright browsers
        run: playwright install
      - name: Run tests
        run: pytest