name: CI

on: [push, pull_request]

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python1
        run: make python-env-create
      - name: Setup python3
        run: make python-env-activate
      - name: Setup python3
        run: make python-env-install
      - name: Run tests
        run: pytest